/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskAiRouteImport } from './routes/ask-ai'
import { Route as DashboardAiRouteImport } from './routes/dashboard-ai'
import { Route as PlanRouteImport } from './routes/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAiRoute = AskAiRouteImport.update({
  id: '/ask-ai',
  path: '/ask-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/dashboard-ai',
  path: '/dashboard-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-ai': typeof AskAiRoute
  '/dashboard-ai': typeof DashboardAiRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-ai': typeof AskAiRoute
  '/dashboard-ai': typeof DashboardAiRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-ai': typeof AskAiRoute
  '/dashboard-ai': typeof DashboardAiRoute
  '/plan': typeof PlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask-ai' | '/dashboard-ai' | '/plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask-ai' | '/dashboard-ai' | '/plan'
  id: '__root__' | '/' | '/ask-ai' | '/dashboard-ai' | '/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskAiRoute: typeof AskAiRoute
  DashboardAiRoute: typeof DashboardAiRoute
  PlanRoute: typeof PlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-ai': {
      id: '/ask-ai'
      path: '/ask-ai'
      fullPath: '/ask-ai'
      preLoaderRoute: typeof AskAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-ai': {
      id: '/dashboard-ai'
      path: '/dashboard-ai'
      fullPath: '/dashboard-ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskAiRoute: AskAiRoute,
  DashboardAiRoute: DashboardAiRoute,
  PlanRoute: PlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
